# Generated by Django 4.2.5 on 2023-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
